"""Generic adaptive skill infrastructure for learnable agent strategies.

An *adaptive skill* is a skill whose content can be mutated by the agent
through typed tool calls — as opposed to read-only skills that are authored
once and never changed by the agent.

The pattern has three layers:

``AdaptiveSkillState`` (abstract)
    A Pydantic model that is the source of truth for a skill's content.
    Concrete subclasses define the domain-specific fields and implement
    ``build_markdown()`` to render those fields into the ``SKILL.md`` text
    that the ADK ``SkillToolset`` injects into the agent's context.

``AdaptiveSkillStore``
    Persistence layer for a concrete ``AdaptiveSkillState``.  Manages three
    artefacts in a skill directory:

    - ``skill_state.yaml`` — serialized state; the source of truth.
    - ``SKILL.md`` — rendered from state on every save; what the agent reads.
    - ``.history/`` — timestamped backups written before each save so that
      every mutation is reversible without git involvement.

    The ``confirmation_threshold`` (how many confirmed hypothesis outcomes are
    required before ``graduate_hypothesis`` is permitted) is a *store*
    parameter, not a *state* field.  This keeps the evidence bar outside the
    agent's reach — the agent cannot lower the bar by mutating state.

Usage pattern
-------------
Define a concrete state and instantiate a store once at module level in the
implementation's ``skill_tools.py``::

    from aieng.forecasting.methods.agentic.adaptive_skill import (
        AdaptiveSkillState,
        AdaptiveSkillStore,
    )


    class MyStrategyState(AdaptiveSkillState):
        approach_narrative: str
        ...

        def build_markdown(self) -> str: ...


    STORE: AdaptiveSkillStore[MyStrategyState] = AdaptiveSkillStore(
        skill_dir=Path(__file__).parent / "skills" / "my-strategy",
        state_type=MyStrategyState,
        confirmation_threshold=3,
    )

Then write one thin tool function per mutation operation and register them via
``AgentConfig(extra_tools=[...])``.
"""

from __future__ import annotations

import shutil
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path
from typing import Generic, TypeVar

import yaml
from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------


class AdaptiveSkillState(BaseModel, ABC):
    """Abstract base for skill states that an agent can modify through typed tool calls.

    Subclasses define domain-specific fields (observations, hypotheses,
    calibration corrections, etc.) and implement ``build_markdown()`` to
    render those fields into a complete ``SKILL.md`` document — including
    YAML frontmatter.

    The rendered ``SKILL.md`` is what the ADK ``SkillToolset`` loads and
    injects into the agent's context.  The state itself is serialized to
    ``skill_state.yaml`` as the authoritative source of truth.
    """

    schema_version: str = "1.0"

    @abstractmethod
    def build_markdown(self, skill_name: str | None = None) -> str:
        """Render the current state to full ``SKILL.md`` content.

        The output must include valid YAML frontmatter (``---`` fences) at the
        top so that ``load_skill_from_dir`` can parse the skill metadata.

        Parameters
        ----------
        skill_name : str or None
            The value to embed in the frontmatter ``name:`` field.  Must match
            the containing directory name exactly (ADK enforces this).  When
            ``None``, subclasses should fall back to their default skill name.

        Returns
        -------
        str
            Complete ``SKILL.md`` text, ready to write to disk.
        """
        ...


# ---------------------------------------------------------------------------
# Generic store
# ---------------------------------------------------------------------------

S = TypeVar("S", bound=AdaptiveSkillState)

_YAML_STATE_FILENAME = "skill_state.yaml"
_SKILL_MD_FILENAME = "SKILL.md"
_HISTORY_DIR = ".history"
_GENERATED_HEADER = "<!-- Generated by AdaptiveSkillStore — do not edit by hand. -->\n"


class AdaptiveSkillStore(Generic[S]):
    """Persistence layer for an :class:`AdaptiveSkillState`.

    Manages the three artefacts in a skill directory:

    - ``skill_state.yaml`` — YAML-serialised state (source of truth).
    - ``SKILL.md`` — rendered from state on every save.
    - ``.history/`` — timestamped backups for reversibility.

    Parameters
    ----------
    skill_dir : Path
        Directory containing the skill (the one passed to
        ``load_skill_from_dir``).  Must exist.
    state_type : type[S]
        Concrete ``AdaptiveSkillState`` subclass.  Used for deserialisation.
    confirmation_threshold : int, default=3
        Minimum ``confirmations`` count a hypothesis must reach before
        ``graduate_hypothesis`` is allowed to promote it to a calibration
        correction.  Kept here (not in state) so the agent cannot lower it.
    """

    def __init__(
        self,
        skill_dir: Path,
        state_type: type[S],
        confirmation_threshold: int = 3,
    ) -> None:
        if not skill_dir.is_dir():
            raise ValueError(f"Skill directory does not exist: {skill_dir}")
        self._skill_dir = skill_dir
        self._state_type = state_type
        self.confirmation_threshold = confirmation_threshold

    # ------------------------------------------------------------------
    # Paths
    # ------------------------------------------------------------------

    @property
    def state_path(self) -> Path:
        """Path to ``skill_state.yaml``."""
        return self._skill_dir / _YAML_STATE_FILENAME

    @property
    def skill_md_path(self) -> Path:
        """Path to the rendered ``SKILL.md``."""
        return self._skill_dir / _SKILL_MD_FILENAME

    @property
    def history_dir(self) -> Path:
        """Path to the ``.history/`` backup directory."""
        return self._skill_dir / _HISTORY_DIR

    # ------------------------------------------------------------------
    # Load / save
    # ------------------------------------------------------------------

    def load(self) -> S:
        """Deserialise state from ``skill_state.yaml``.

        Raises
        ------
        FileNotFoundError
            If ``skill_state.yaml`` does not exist.  Seed it first with
            ``save(initial_state)`` before registering mutation tools.
        """
        if not self.state_path.exists():
            raise FileNotFoundError(
                f"skill_state.yaml not found in {self._skill_dir}. Run the seed script to initialise the skill state."
            )
        raw = yaml.safe_load(self.state_path.read_text(encoding="utf-8"))
        return self._state_type.model_validate(raw)

    def save(self, state: S) -> str:
        """Persist *state* to disk and re-render ``SKILL.md``.

        Steps:

        1. Back up the current ``skill_state.yaml`` to ``.history/`` with a
           UTC ISO-8601 timestamp suffix (before overwriting).
        2. Write ``skill_state.yaml`` from ``state.model_dump()``.
        3. Re-render ``SKILL.md`` via ``state.build_markdown()``.

        Parameters
        ----------
        state : S
            Updated state to persist.

        Returns
        -------
        str
            Human-readable confirmation message suitable for returning from a
            tool call.
        """
        # 1. Backup
        if self.state_path.exists():
            self.history_dir.mkdir(exist_ok=True)
            ts = datetime.now(tz=timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            backup_path = self.history_dir / f"skill_state_{ts}.yaml"
            shutil.copy2(self.state_path, backup_path)

        # 2. Write YAML state
        data = state.model_dump(mode="json")
        self.state_path.write_text(
            yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )

        # 3. Re-render SKILL.md — pass dir name so frontmatter matches ADK requirement
        rendered = state.build_markdown(skill_name=self._skill_dir.name)
        self.skill_md_path.write_text(rendered, encoding="utf-8")

        return f"State saved to {self.state_path.name}. SKILL.md re-rendered. Backup written to {_HISTORY_DIR}/."
